### ISSUE TITLE
Error on linux with the new version

### ISSUE THREAD

**Issue by 4n0nct** [Dadido3/D3pixelbot#10]
Hello, I've tried it, but cant build or run anything.
Did I miss something ?
![2019-06-19_16-36](https://user-images.githubusercontent.com/50212348/59774822-681ad880-92b0-11e9-9e2a-a8c9bdefd4a0.png)

**Comment by Dadido3** [comment]
Oh, i didn't knew that `FileTime` is only available on windows.
I'll look for a lib that does the same thing

**Comment by Dadido3** [comment]
Ok, pushed an update. It should compile now

**Comment by Dadido3** [comment]
It's the library for the user interface.
You can get it in compiled form from [here](https://github.com/c-smile/sciter-sdk/tree/master/bin.gtk/x64), but no idea if there is also a x86 linux build available too, if needed.

Place it either into the same directory as the executable, or into `/usr/local/lib`, `/usr/local/lib64`, `/usr/lib` or /usr/lib64`. No idea which is the correct path, as i don't have a linux here to test it right now.

**Comment by 4n0nct** [comment]
I will try that thx.

**Comment by 4n0nct** [comment]
there is some progress:
`[sciter-x-api.c] Unable to load library: /usr/lib/libsciter-gtk.so: invalid ELF header`
`[sciter-x-api.c] Unable to load library: /home/x/D3pixelbot/libsciter-gtk.so: invalid ELF header`

**Comment by Dadido3** [comment]
Did you compile D3pixelbot as x86 or x86-64? Or something completely different?
Also, do the other executables [in here](https://github.com/c-smile/sciter-sdk/tree/master/bin.gtk/x64) (like `./usciter`) have the same problem?

**Comment by 4n0nct** [comment]
As x86-64.
`The file './usciter' is marked as an executable but could not be run by the operating system`
(I had to chmod +x first)
I will retry later, thank you for your time.

**Comment by Dadido3** [comment]
Closing this, as there are automatic linux builds now
